from simplemma.strategies.defaultrules import DEFAULT_RULES


def test_apply_de() -> None:
    """Test German rules."""
    # doesn't exist
    assert DEFAULT_RULES["de"]("Whatawordicantbelieveit") is None
    # nouns
    # assert DEFAULT_RULES["de"]("Besorgnis") == "Besorgnis"
    # assert DEFAULT_RULES["de"]("Besorgnisse") == "Besorgnis"
    # assert DEFAULT_RULES["de"]("Abonnenten") == "Abonnent"
    assert DEFAULT_RULES["de"]("Pfifferling") == "Pfifferling"
    assert DEFAULT_RULES["de"]("Pfifferlinge") == "Pfifferling"
    assert DEFAULT_RULES["de"]("Pfifferlingen") == "Pfifferling"
    assert DEFAULT_RULES["de"]("Heiterkeiten") == "Heiterkeit"
    # assert DEFAULT_RULES["de"]("Bahnreisenden") == "Bahnreisende"
    assert DEFAULT_RULES["de"]("Bürgertums") == "Bürgertum"
    assert DEFAULT_RULES["de"]("Achterls") == "Achterl"
    # assert DEFAULT_RULES["de"]("Inspekteurinnen") == "Inspekteurin"
    # assert DEFAULT_RULES["de"]("Zwiebelschneider") == "Zwiebelschneider"
    # assert DEFAULT_RULES["de"]("Zwiebelschneiders") == "Zwiebelschneider"
    # assert DEFAULT_RULES["de"]("Schneidern") == "Schneider"
    # assert DEFAULT_RULES["de"]("Bedenkens") == "Bedenken"
    # assert DEFAULT_RULES["de"]("Facetten") == "Facette"
    assert DEFAULT_RULES["de"]("Kazakhstans") == "Kazakhstan"
    # assert DEFAULT_RULES["de"]("Hämatome") == "Hämatom"
    # assert DEFAULT_RULES["de"]("Hämatomen") == "Hämatom"
    # assert DEFAULT_RULES["de"]("Hämatoms") == "Hämatom"
    assert DEFAULT_RULES["de"]("Ökonomen") == "Ökonom"
    assert DEFAULT_RULES["de"]("Chauffeusen") == "Chauffeuse"
    # assert DEFAULT_RULES["de"]("Bibliotheken") == "Bibliothek"
    assert DEFAULT_RULES["de"]("Kazakhstans") == "Kazakhstan"
    # assert DEFAULT_RULES["de"]("Gymnasiasten") == "Gymnasiast"
    # assert DEFAULT_RULES["de"]("Dezernates") == "Dezernat"
    assert DEFAULT_RULES["de"]("Luftikussen") == "Luftikus"
    assert DEFAULT_RULES["de"]("Trunkenbolde") == "Trunkenbold"
    assert DEFAULT_RULES["de"]("Theologien") == "Theologie"
    # assert DEFAULT_RULES["de"]("Geschädigten") == "Geschädigte"
    # assert DEFAULT_RULES["de"]("Zeitschriftenmarken") == "Zeitschriftenmarke"
    # assert DEFAULT_RULES["de"]("Gesundheitsfreaks") == "Gesundheitsfreak"
    # adjectives
    assert DEFAULT_RULES["de"]("großartiges") == "großartig"
    # assert DEFAULT_RULES["de"]("achtsame") == "achtsam"
    # assert DEFAULT_RULES["de"]("aufgemachtes") == "aufgemacht"
    # assert DEFAULT_RULES["de"]("schnellster") == "schnell"
    # assert DEFAULT_RULES["de"]("geächteten") == "geächtet"
    # assert DEFAULT_RULES["de"]("aufgeblasenes") == "aufgeblasen"
    # assert DEFAULT_RULES["de"]("viszerale") == "viszeral"
    # assert DEFAULT_RULES["de"]("kurioses") == "kurios"
    # assert DEFAULT_RULES["de"]("adipösen") == "adipös"
    assert DEFAULT_RULES["de"]("isotropen") == "isotrop"
    # assert DEFAULT_RULES["de"]("kulanten") == "kulant"
    # assert DEFAULT_RULES["de"]("konvexes") == "konvex"
    # assert DEFAULT_RULES["de"]("myope") == "myop"
    # assert DEFAULT_RULES["de"]("geschleunigst") == "geschleunig"
    # assert DEFAULT_RULES["de"]("zweitrangigster") == "zweitrangig"
    # assert DEFAULT_RULES["de"]("kompetenteste") == "kompetent"
    # assert DEFAULT_RULES["de"]("leiwandste") == "leiwand"
    # assert DEFAULT_RULES["de"]("gescheitesten") == "gescheit"
    # assert DEFAULT_RULES["de"]("luzidesten") == "luzide"  # luzid?
    # assert DEFAULT_RULES["de"]("frigides") == "frigide"
    # assert DEFAULT_RULES["de"]("frigideren") == "frigide"
    # assert DEFAULT_RULES["de"]("kruden") == "krude"
    # assert DEFAULT_RULES["de"]("krudesten") == "krude"
    # assert DEFAULT_RULES["de"]("zwielichtigen") == "zwielichtig"
    # assert DEFAULT_RULES["de"]("freakige") == "freakig"
    # assert DEFAULT_RULES["de"]("plausibles") == "plausibel"
    # assert DEFAULT_RULES["de"]("propres") == "proper"
    # assert DEFAULT_RULES["de"]("perlende") == "perlend"
    # assert DEFAULT_RULES["de"]("wuchernder") == "wuchernd"
    assert DEFAULT_RULES["de"]("angebrachtes") == "angebracht"
    # Gendersprache normalization
    assert DEFAULT_RULES["de"]("ZuschauerInnen") == "Zuschauer:innen"
    assert DEFAULT_RULES["de"]("Zuschauer*innen") == "Zuschauer:innen"
    assert DEFAULT_RULES["de"]("Zuschauer_innen") == "Zuschauer:innen"
    assert DEFAULT_RULES["de"]("Zuschauer-innen") == "Zuschauer:innen"
