# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14', '3.15-dev']
        env: [{ MINIMAL: "true" }, { MINIMAL: "false" }]
        include:
        # common versions on MacOS
        - os: macos-latest
          python-version: '3.10'
        - os: macos-latest
          python-version: '3.12'
        # common versions on Windows
        - os: windows-latest
          python-version: '3.10'
        - os: windows-latest
          python-version: '3.12'

    steps:
    # package setup
    - uses: actions/checkout@v4

    # Python and uv setup
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install dependencies
      run: uv sync --extra dev

    - name: Install full dependencies
      if: ${{ matrix.env.MINIMAL == 'false'}}
      run: uv sync --extra dev --extra marisa-trie

    # tests
    - name: Lint with ruff
      run: uv run ruff check .

    - name: Code format with ruff
      run: uv run ruff format --check simplemma training tests

    - name: Type checking with mypy
      run: uv run mypy -p simplemma -p training -p tests

    - name: Test with pytest
      run: uv run pytest --cov=./ --cov-report=xml

    # coverage with default version
    - name: Upload coverage to Codecov
      if: ${{ matrix.env.MINIMAL == 'false' && matrix.python-version == '3.13' }}
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        fail_ci_if_error: true
        files: ./coverage.xml
        verbose: true
